export const dashboardT = {
  "nav": {
    "dashboard": "Dashboard",
    "testHistory": "Test History",
    "profile": "Profile",
    "billing": "Billing",
    "freePlan": "Free plan",
    "signOut": "Sign out",
    "loggedOut": "Logged out successfully!"
  },
  "welcome": "Welcome back",
  "subtitle": "Manage your automated testing campaigns",
  "stats": {
    "totalTests": "Total Tests",
    "successRate": "Success Rate",
    "avgScore": "Avg Score",
    "bestScore": "Best Score",
    "thisMonth": "This Month",
    "totalPassed": "Total Passed",
    "avgDuration": "Avg Duration",
    "creditsLeft": "Credits Left",
    "completed": "completed",
    "failed": "failed",
    "goodHealth": "Good health",
    "needsReview": "Needs review",
    "allTimeHigh": "All time high",
    "loading": "Loading…",
    "perTestRun": "Per test run"
  },
  "runTests": {
    "title": "Run Web Tests",
    "subtitle": "Upload source code to start automated AI testing",
    "zip": "ZIP",
    "github": "GitHub",
    "readyToTest": "Ready to test",
    "dragDrop": "Drag & drop your .zip here",
    "or": "or",
    "browseFiles": "browse files",
    "maxSize": "Max 200 MB",
    "connectGithub": "Connect your GitHub account",
    "githubPermission": "TestPilot will request read access to clone public and private repos",
    "connectBtn": "Connect GitHub",
    "connected": "Connected",
    "reconnect": "Reconnect",
    "repository": "Repository",
    "searchRepos": "Search your repos…",
    "loadingRepos": "Loading repositories…",
    "private": "Private",
    "branch": "Branch",
    "testType": "Test Type",
    "uiTesting": "UI Testing",
    "apiTesting": "API Testing",
    "functionalTesting": "Functional Testing",
    "uiUx": "UI/UX",
    "endpoints": "Endpoints",
    "function": "Function",
    "aiPowered": "AI-powered test generation & execution",
    "startTesting": "Start Testing",
    "starting": "Starting…"
  },
  "lastResult": {
    "title": "Last Test Result",
    "noResults": "No results yet",
    "noResultsHint": "Run your first test to see stats",
    "healthScore": "Health Score",
    "healthy": "Healthy",
    "fair": "Fair",
    "critical": "Critical",
    "passed": "Passed",
    "failed": "Failed",
    "total": "Total",
    "duration": "Duration:",
    "issues": "Issue(s)"
  },
  "credits": {
    "warning": "Credits running low",
    "remaining": "remaining",
    "hint": "Top up now to avoid interruptions during test runs.",
    "topUp": "Top Up"
  },
  "history": {
    "title": "Test History",
    "runs": "runs · saved to your account",
    "completed": "completed",
    "failed": "failed",
    "success": "success",
    "project": "Project",
    "started": "Started",
    "duration": "Duration",
    "status": "Status",
    "passedFailed": "Passed / Failed",
    "score": "Score",
    "report": "Report",
    "empty": "No test history yet",
    "emptyHint": "Run your first test to see results here"
  },
  "toasts": {
    "githubConnected": "GitHub connected",
    "githubFailed": "GitHub connection failed",
    "selectZip": "Please select a .zip file",
    "githubExpired": "GitHub token expired. Please reconnect.",
    "selectZipFirst": "Please select a .zip file first",
    "selectRepo": "Please select a repository",
    "pipelineStarted": "Test pipeline started!",
    "cloningStarted": "pipeline started!",
    "startFailed": "Failed to start test"
  }
};
